twist0: "/wheels/data"
twist0_config: [false, false, false,
                false, false, false,
                true, true, false,
                false, false, false,
                false, false, false]

imu0: "/imu/data"
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
