#!/usr/bin/bash
./src/catkin/bin/catkin_make_isolated -j4 --install --install-space /opt/ros/kinetic -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so
